-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,"%Y") YEAR,MONTH(SALES_DATE) MONTH,GENDER,COUNT(distinct U.USER_ID) AS USERS
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY DATE_FORMAT(SALES_DATE,"%Y"),DATE_FORMAT(SALES_DATE,"%m"),GENDER
ORDER BY DATE_FORMAT(SALES_DATE,"%Y"),DATE_FORMAT(SALES_DATE,"%m"),GENDER